# Generated by Django 3.1.7 on 2021-04-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210402_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_products', to='orders.order'),
        ),
    ]
